<a href="https://colab.research.google.com/github/dohyeon-kim012/MachineLearning-DeepLearning/blob/main/DeepLearning/03.%EB%82%B4%EC%A0%81%2C%20%EB%8B%A4%EC%B0%A8%EC%9B%90%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

배열의 정보 확인

In [ ]:
A = np.array([1, 2, 3, 4])

print(A.ndim)
print(A.shape)

1
(4,)


shape이 (x, )인 것은 편향, 출력값밖에 없음

In [ ]:
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print(B.ndim)
print(B.shape)  # 1차원 배열 3개, 스칼라 2개 -> (3, 2)

2
(3, 2)


# 행렬의 내적

2차원 배열인 행렬의 내적을 구하는 방법?  

$$
\begin{pmatrix}
a & b \\
c & d \\
\end{pmatrix}
\cdot
\begin{pmatrix} 
p & q \\
r & s \\
\end{pmatrix}
= \begin{pmatrix} 
ap+br & aq+bs \\
cp+dr & cq+ds \\
\end{pmatrix}
$$

행렬의 내적은 
* 왼쪽 행렬의 행(가로)와 오른쪽 행렬의 열(세로)를 원소 별로 곱하고 그 값들을 더한다
* 계산의 결과가 새로운 다차원 배열의 원소가 된다
* 행렬은 보통 대문자로 표기하는 것이 관례이다


In [ ]:
# 내적 해보기

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A.shape : {}".format(A.shape))
print("B.shape : {}".format(B.shape))

A.shape : (2, 2)
B.shape : (2, 2)


A.shape(a, b) / B.shape(c, d)  
두 행렬에서 b와 c의 값이 같으면 내적 가능!

In [ ]:
# 내적의 결과 프린트해서 확인
print(np.dot(A, B))
print()
print(A @ B)  # 두 개의 표현은 같은 공식임

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


### 행렬 내적의 특징

* 교환 법칙 성립되지 않는다   $
A \cdot B \ne B \cdot A
$


In [ ]:
B @ A

array([[23, 34],
       [31, 46]])

## 행과 열의 개수가 다른 상태에서의 행렬 내적

첫 번째 행렬의 첫 번째 차원의 원소 수(열의 수)와 두 번째 행렬의 0번째 차원의 원소 수(행의 수)가 일치해야 한다

In [ ]:
A = np.arange(1, 7).reshape(2, 3)  # 2행 3열의 배열 생성
B = np.arange(1, 7).reshape(3, 2)

print(A.shape)
print(B.shape)

(2, 3)
(3, 2)


앞 행렬의 뒤 숫자와 뒤 행렬의 앞 숫자가 둘 다 3으로 같기 때문에 두 행렬은 내적 가능!

In [ ]:
A @ B

array([[22, 28],
       [49, 64]])

In [ ]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

A.shape(a, b) / B.shape(c, d)  
a, c : 출력될 배열의 shape  
a : 행의 수 - 1차원 , c : 열의 수(스칼라) - 0차원

In [ ]:
C = np.arange(1, 5).reshape(2, 2)

print(A.shape)
print(C.shape)

(2, 3)
(2, 2)


위의 상태에서는 A @ C는 불가능하다  
다만, C @ A 는 가능! (2, 3 배열로 출력)

In [ ]:
C @ A

array([[ 9, 12, 15],
       [19, 26, 33]])

## 차원 수가 다른 상태에서의 행렬 내적

In [ ]:
A = A.reshape(3, 2)
B = np.array([7, 8])

print(A.shape)
print(B.shape)

(3, 2)
(2,)


In [ ]:
A @ B

array([23, 53, 83])

B가 1차원 배열이지만 열 벡터로 계산하여 내적 가능함  

계산이 안 맞기 때문에 B @ A 는 내적 안 됨